# Generated by Django 5.2.8 on 2025-12-01 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='register',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='register',
            name='role',
        ),
        migrations.RemoveField(
            model_name='register',
            name='username',
        ),
        migrations.AlterField(
            model_name='register',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
