# Generated by Django 5.2.8 on 2025-12-01 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_register_managers_remove_register_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='role',
            field=models.CharField(default='user', max_length=20),
        ),
    ]
